### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by Paulls20** [ros2/ros1_bridge#144]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04.1 LTS
- Installation type:
  - From source
- Version or commit hash:
  - git rev-parse HEAD 6ec7e8d7e0aadb2b3ae6afedbe0c6250a59a4df2
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Compilation error:
```bash
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws/src
git clone https://github.com/ros2/ros1_bridge.git
cd ..
source /opt/ros/melodic/setup.bash
source /opt/ros/bouncy/local_setup.bash
colcon build --symlink-install --packages-select ros1_bridge --cmake-force-configure
```
```bash
~/ros2_ws/src/ros1_bridge/include/ros1_bridge/factory.hpp:166:85: error: request for member ‘str’ in ‘rcutils_get_error_string()’, which is of non-class type ‘const char*’
         auto msg = std::string("Failed to compare gids: ") + rmw_get_error_string().str;
                                                                                     ^~~
```
#### Expected behavior
Compilation should be successful.
#### Actual behavior
Compilation error
#### Additional information
Fixed the problem by changing the following line ros1_bridge/include/ros1_bridge/factory.hpp +166
```C++
auto msg = std::string("Failed to compare gids: ") + rmw_get_error_string().str;
to
auto msg = std::string("Failed to compare gids: ") + rmw_get_error_string();
```

**Comment by clalancette** [comment]
The problem here is that we have changed APIs since bouncy, so the master branch of https://github.com/ros2/ros1_bridge.git will not build against bouncy anymore.  You'll either have to build all of ros2 from source https://index.ros.org/doc/ros2/Installation/, or you'll have to use the "bouncy" branch from https://github.com/ros2/ros1_bridge/tree/bouncy .  I'm going to close this out for now, but feel free to reopen if you have trouble with either of those options.
