### ISSUE TITLE
convert 'tf/tfMessage' from ROS1 rosbag to ROS2 'tf2_msgs/msg/TFMessage', show nothing 

### ISSUE THREAD

**Issue by EgalYue** [ros2/ros1_bridge#219]
Hi,
I met one problem, when I want to get `/tf` message from my rosbag or from TUM dataset rosbag?

I installed and built `ros1_bridge` from source.
I run this in a docker container:
ros2: dashing (using the provided debs)
ros1: melodic (using the provided debs)

**The following are my steps:**
Step 1: Open shell 1:
```
. /opt/ros/melodic/setup.bash
. /opt/ros/dashing/setup.bash
. ./bridge_ws/install/setup.bash
ros2 bag info -s rosbag_v2 rgbd_dataset_freiburg1_rpy.bag
ros2 bag play -s rosbag_v2 rgbd_dataset_freiburg1_rpy.bag

```
![terminal2](https://user-images.githubusercontent.com/19492574/64501713-1739df80-d2f5-11e9-8e1b-0a6b69d7eef9.png)

 And the type of  `/tf` topic is `tf2_msgs/msg/TFMessage`, it looks ok.

Step 2: Open shell 2:
```
. /opt/ros/melodic/setup.bash
. /opt/ros/dashing/setup.bash
. ./bridge_ws/install/setup.bash
ros2 topic list
ros2 topic echo /tf
```
![terminal3](https://user-images.githubusercontent.com/19492574/64501805-93342780-d2f5-11e9-890a-a9dd86cf5f82.png)

**topic `/tf` showed nothing!**

Please help !
Thank you!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
