### ISSUE TITLE
Need to use with gazebo11. How to get rid of gazebo-msgs dependency(which uses gazebo 9 )

### ISSUE THREAD

**Issue by Harsharma2308** [ros2/ros1_bridge#281]
**Required Info:**

- Operating System:
Ubuntu 18.04
- Installation type:
BInaries
I am using ROS Eloquent. I need to use Gazebo 11 because of a known issue in gazebo9.
For this reason the dependecy `ros-melodic-gazebo-msgs` conflicts with my current installation of `ros-melodic-gazebo11-*`. How do I get around this?
Thanks

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
